# Generated by Django 4.2.20 on 2025-06-18 21:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usersettings', '0005_checkbox_for_setting_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reedsetting',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
