# Generated by Django 4.2.20 on 2025-06-21 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usersettings', '0006_reedsetting_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reedsetting',
            old_name='thicness',
            new_name='thickness',
        ),
    ]
