# Generated by Django 4.2.20 on 2025-06-22 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersettings', '0007_rename_thicness_reedsetting_thickness'),
    ]

    operations = [
        migrations.AddField(
            model_name='reedsetting',
            name='density_auto',
            field=models.BooleanField(default=True),
        ),
    ]
