# Generated by Django 4.2.20 on 2025-06-22 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usersettings', '0008_reedsetting_density_auto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reedsetting',
            name='density_auto',
        ),
    ]
