# Generated by Django 5.2.3 on 2025-07-01 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usersettings", "0009_remove_reedsetting_density_auto"),
    ]

    operations = [
        migrations.AddField(
            model_name="reedsetting",
            name="profile_model",
            field=models.BooleanField(default=True),
        ),
    ]
