# Generated by Django 4.2.20 on 2025-06-12 20:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reedsdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluation', models.IntegerField(blank=True, choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], null=True)),
                ('reed_ID', models.CharField(max_length=220, null=True, unique=True)),
                ('cane_brand', models.CharField(max_length=220, null=True)),
                ('gouging_machine', models.CharField(max_length=220, null=True)),
                ('cane_diamater', models.IntegerField(blank=True, default=None, null=True)),
                ('thicness', models.FloatField(blank=True, default=None, null=True)),
                ('hardness', models.FloatField(blank=True, default=None, null=True)),
                ('flexibility', models.FloatField(blank=True, default=None, null=True)),
                ('density', models.FloatField(blank=True, default=None, null=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('shaper', models.CharField(default=None, max_length=220)),
                ('harvest_year', models.CharField(default=None, max_length=220)),
                ('temperature', models.FloatField(blank=True, default=None, null=True)),
                ('humidity', models.FloatField(blank=True, default=None, null=True)),
                ('reedauthor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
