# Generated by Django 4.2.20 on 2025-06-15 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reedsdata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reedsdata',
            name='cane_brand',
            field=models.CharField(blank=True, default=None, max_length=220, null=True),
        ),
        migrations.AlterField(
            model_name='reedsdata',
            name='gouging_machine',
            field=models.CharField(blank=True, max_length=220, null=True),
        ),
        migrations.AlterField(
            model_name='reedsdata',
            name='harvest_year',
            field=models.CharField(blank=True, default=None, max_length=220),
        ),
        migrations.AlterField(
            model_name='reedsdata',
            name='shaper',
            field=models.CharField(blank=True, default=None, max_length=220),
        ),
    ]
