# Generated by Django 4.2.20 on 2025-06-15 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reedsdata', '0002_alter_reedsdata_cane_brand_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='reedsdata',
            constraint=models.UniqueConstraint(fields=('reed_ID', 'reedauthor'), name='name of constraint'),
        ),
    ]
