# Generated by Django 4.2.20 on 2025-06-15 21:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reedsdata', '0003_reedsdata_name_of_constraint'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='reedsdata',
            name='name of constraint',
        ),
        migrations.AlterField(
            model_name='reedsdata',
            name='reed_ID',
            field=models.CharField(max_length=220, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='reedsdata',
            unique_together={('reed_ID', 'reedauthor')},
        ),
    ]
