# Generated by Django 4.2.20 on 2025-06-15 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reedsdata', '0004_remove_reedsdata_name_of_constraint_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reedsdata',
            name='harvest_year',
            field=models.CharField(blank=True, default=None, max_length=220, null=True),
        ),
        migrations.AlterField(
            model_name='reedsdata',
            name='shaper',
            field=models.CharField(blank=True, default=None, max_length=220, null=True),
        ),
    ]
