# Generated by Django 4.2.20 on 2025-06-18 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reedsdata', '0005_alter_reedsdata_harvest_year_alter_reedsdata_shaper'),
    ]

    operations = [
        migrations.AddField(
            model_name='reedsdata',
            name='global_quality',
            field=models.IntegerField(blank=True, choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=None, null=True),
        ),
        migrations.AddField(
            model_name='reedsdata',
            name='intonation',
            field=models.IntegerField(blank=True, choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=None, null=True),
        ),
        migrations.AddField(
            model_name='reedsdata',
            name='perceived_stiffness',
            field=models.IntegerField(blank=True, choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=None, null=True),
        ),
        migrations.AddField(
            model_name='reedsdata',
            name='playing_ease',
            field=models.IntegerField(blank=True, choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=None, null=True),
        ),
        migrations.AddField(
            model_name='reedsdata',
            name='response_time',
            field=models.IntegerField(blank=True, choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=None, null=True),
        ),
        migrations.AddField(
            model_name='reedsdata',
            name='tone_color',
            field=models.IntegerField(blank=True, choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=None, null=True),
        ),
    ]
