# Generated by Django 4.2.20 on 2025-06-18 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reedsdata', '0006_reedsdata_global_quality_reedsdata_intonation_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reedsdata',
            old_name='cane_diamater',
            new_name='diamater',
        ),
        migrations.RenameField(
            model_name='reedsdata',
            old_name='perceived_stiffness',
            new_name='response',
        ),
        migrations.RenameField(
            model_name='reedsdata',
            old_name='response_time',
            new_name='stiffness',
        ),
    ]
