# Generated by Django 4.2.20 on 2025-06-21 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reedsdata', '0007_rename_cane_diamater_reedsdata_diamater_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reedsdata',
            old_name='thicness',
            new_name='thickness',
        ),
    ]
