# Generated by Django 4.2.20 on 2025-06-22 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reedsdata', '0008_rename_thicness_reedsdata_thickness'),
    ]

    operations = [
        migrations.AddField(
            model_name='reedsdata',
            name='density_auto',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reedsdata',
            name='m1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reedsdata',
            name='m2',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
