# Generated by Django 4.2.20 on 2025-06-22 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reedsdata', '0009_reedsdata_density_auto_reedsdata_m1_reedsdata_m2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reedsdata',
            name='density_auto',
        ),
        migrations.AddField(
            model_name='reedsdata',
            name='density_mode',
            field=models.CharField(choices=[('manual', 'Manual'), ('auto', 'Auto from M1 and M2')], default='manual', max_length=10),
        ),
    ]
