# Generated by Django 4.2.20 on 2025-06-22 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reedsdata', '0010_remove_reedsdata_density_auto_reedsdata_density_mode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reedsdata',
            old_name='m1',
            new_name='density_m1',
        ),
        migrations.RenameField(
            model_name='reedsdata',
            old_name='m2',
            new_name='density_m2',
        ),
        migrations.RemoveField(
            model_name='reedsdata',
            name='density_mode',
        ),
        migrations.AddField(
            model_name='reedsdata',
            name='density_auto',
            field=models.BooleanField(default=False),
        ),
    ]
