# Generated by Django 4.2.20 on 2025-06-22 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reedsdata', '0011_rename_m1_reedsdata_density_m1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reedsdata',
            name='density_auto',
        ),
        migrations.RemoveField(
            model_name='reedsdata',
            name='density_m1',
        ),
        migrations.RemoveField(
            model_name='reedsdata',
            name='density_m2',
        ),
    ]
