# Generated by Django 4.2.20 on 2025-06-22 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reedsdata', '0012_remove_reedsdata_density_auto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reedsdata',
            name='density_auto',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reedsdata',
            name='m1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reedsdata',
            name='m2',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
