# Generated by Django 4.2.20 on 2025-06-22 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reedsdata', '0013_reedsdata_density_auto_reedsdata_m1_reedsdata_m2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reedsdata',
            name='density_auto',
        ),
    ]
