# Generated by Django 5.2.3 on 2025-07-01 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reedsdata", "0014_remove_reedsdata_density_auto"),
    ]

    operations = [
        migrations.AddField(
            model_name="reedsdata",
            name="instrument",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="reedsdata",
            name="profile_model",
            field=models.CharField(blank=True, max_length=220, null=True),
        ),
        migrations.AddField(
            model_name="reedsdata",
            name="staple_model",
            field=models.CharField(max_length=20, null=True),
        ),
    ]
