# Generated by Django 4.2.20 on 2026-01-20 13:09

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reedsdata', '0015_reedsdata_instrument_reedsdata_profile_model_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cane',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reed_ID', models.CharField(max_length=20)),
                ('instrument', models.CharField(max_length=20)),
                ('staple_model', models.CharField(blank=True, max_length=20, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('display_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='reedsdata',
            name='diamater',
        ),
        migrations.RemoveField(
            model_name='reedsdata',
            name='evaluation',
        ),
        migrations.RemoveField(
            model_name='reedsdata',
            name='global_quality',
        ),
        migrations.AddField(
            model_name='reedsdata',
            name='air_pressure',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Air pressure in hPa', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='reedsdata',
            name='bed_diameter',
            field=models.FloatField(blank=True, help_text='in mm', null=True),
        ),
        migrations.AddField(
            model_name='reedsdata',
            name='blade_diameter',
            field=models.FloatField(blank=True, help_text='in mm', null=True),
        ),
        migrations.AddField(
            model_name='reedsdata',
            name='chamber_humidity',
            field=models.FloatField(blank=True, default=None, help_text='Chamber humidity percentage', null=True),
        ),
        migrations.AddField(
            model_name='reedsdata',
            name='chamber_temperature',
            field=models.FloatField(blank=True, default=None, help_text='Chamber temperature in Celsius', null=True),
        ),
        migrations.AddField(
            model_name='reedsdata',
            name='counts_concert',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='reedsdata',
            name='counts_rehearsal',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='reedsdata',
            name='diameter',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='reedsdata',
            name='global_quality_first_impression',
            field=models.IntegerField(blank=True, choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=None, null=True),
        ),
        migrations.AddField(
            model_name='reedsdata',
            name='global_quality_first_impression_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reedsdata',
            name='global_quality_first_weather_altitude',
            field=models.IntegerField(blank=True, help_text='Altitude when 1st impression recorded (meters)', null=True),
        ),
        migrations.AddField(
            model_name='reedsdata',
            name='global_quality_first_weather_description',
            field=models.CharField(blank=True, help_text='Weather when 1st impression recorded', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='reedsdata',
            name='global_quality_first_weather_humidity',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Humidity when 1st impression recorded (%)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='reedsdata',
            name='global_quality_first_weather_location',
            field=models.CharField(blank=True, help_text='Location when 1st impression was recorded', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='reedsdata',
            name='global_quality_first_weather_pressure',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Air pressure when 1st impression recorded (hPa)', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='reedsdata',
            name='global_quality_first_weather_temperature',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Temperature when 1st impression recorded (°C)', max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='reedsdata',
            name='global_quality_second_impression',
            field=models.IntegerField(blank=True, choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=None, null=True),
        ),
        migrations.AddField(
            model_name='reedsdata',
            name='global_quality_second_impression_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reedsdata',
            name='global_quality_second_weather_altitude',
            field=models.IntegerField(blank=True, help_text='Altitude when 2nd impression recorded (meters)', null=True),
        ),
        migrations.AddField(
            model_name='reedsdata',
            name='global_quality_second_weather_description',
            field=models.CharField(blank=True, help_text='Weather when 2nd impression recorded', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='reedsdata',
            name='global_quality_second_weather_humidity',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Humidity when 2nd impression recorded (%)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='reedsdata',
            name='global_quality_second_weather_location',
            field=models.CharField(blank=True, help_text='Location when 2nd impression was recorded', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='reedsdata',
            name='global_quality_second_weather_pressure',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Air pressure when 2nd impression recorded (hPa)', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='reedsdata',
            name='global_quality_second_weather_temperature',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Temperature when 2nd impression recorded (°C)', max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='reedsdata',
            name='global_quality_third_impression',
            field=models.IntegerField(blank=True, choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=None, null=True),
        ),
        migrations.AddField(
            model_name='reedsdata',
            name='global_quality_third_impression_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reedsdata',
            name='global_quality_third_weather_altitude',
            field=models.IntegerField(blank=True, help_text='Altitude when 3rd impression recorded (meters)', null=True),
        ),
        migrations.AddField(
            model_name='reedsdata',
            name='global_quality_third_weather_description',
            field=models.CharField(blank=True, help_text='Weather when 3rd impression recorded', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='reedsdata',
            name='global_quality_third_weather_humidity',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Humidity when 3rd impression recorded (%)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='reedsdata',
            name='global_quality_third_weather_location',
            field=models.CharField(blank=True, help_text='Location when 3rd impression was recorded', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='reedsdata',
            name='global_quality_third_weather_pressure',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Air pressure when 3rd impression recorded (hPa)', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='reedsdata',
            name='global_quality_third_weather_temperature',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Temperature when 3rd impression recorded (°C)', max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='reedsdata',
            name='location',
            field=models.CharField(blank=True, help_text='City or venue name', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='reedsdata',
            name='note',
            field=models.CharField(blank=True, help_text='Additional notes', max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='reedsdata',
            name='shaper_model',
            field=models.CharField(blank=True, default=None, help_text='Specific model or shape number', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='reedsdata',
            name='weather_description',
            field=models.CharField(blank=True, help_text="e.g., 'Clear sky', 'Light rain'", max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='reedsdata',
            name='cane_brand',
            field=models.CharField(choices=[('', ''), ('Medir', 'Medir'), ('Rigotti', 'Rigotti'), ('Ghys', 'Ghys'), ('Glotin', 'Glotin'), ('Pisoni', 'Pisoni'), ("Reeds 'n Stuff", "Reeds 'n Stuff"), ('Danzi', 'Danzi'), ('Arundo Donax', 'Arundo Donax'), ('Marca', 'Marca'), ('Gonzalez', 'Gonzalez'), ('Silvacane', 'Silvacane'), ('Emerald', 'Emerald'), ('Baron', 'Baron'), ('Milliet', 'Milliet'), ('Vandoren', 'Vandoren'), ('Jones', 'Jones'), ('Gilbert', 'Gilbert'), ('Marigaux', 'Marigaux'), ('Loree', 'Loree'), ('Fox', 'Fox'), ('Hiniker', 'Hiniker'), ('Bonazza', 'Bonazza'), ('Chartier', 'Chartier'), ('Other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='reedsdata',
            name='density',
            field=models.FloatField(blank=True, default=None, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2.0)]),
        ),
        migrations.AlterField(
            model_name='reedsdata',
            name='flexibility',
            field=models.FloatField(blank=True, default=None, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='reedsdata',
            name='gouging_machine',
            field=models.CharField(blank=True, choices=[('', ''), ("Reeds 'n Stuff", "Reeds 'n Stuff"), ('Graf', 'Graf'), ('Ross', 'Ross'), ('Rieger', 'Rieger'), ('Innoledy', 'Innoledy'), ('Weber', 'Weber'), ('Kunibert Michel', 'Kunibert Michel'), ('Prestini', 'Prestini'), ('Other', 'Other')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='reedsdata',
            name='hardness',
            field=models.FloatField(blank=True, default=None, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='reedsdata',
            name='harvest_year',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='reedsdata',
            name='humidity',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Humidity percentage', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='reedsdata',
            name='profile_model',
            field=models.CharField(blank=True, choices=[('', ''), ("Reeds 'n Stuff -1", "Reeds 'n Stuff -1"), ("Reeds 'n Stuff -1N", "Reeds 'n Stuff -1N"), ("Reeds 'n Stuff -2", "Reeds 'n Stuff -2"), ("Reeds 'n Stuff -2N", "Reeds 'n Stuff -2N"), ('Philadelphia', 'Philadelphia'), ('Mack', 'Mack'), ('Rieger 1A', 'Rieger 1A'), ('Rieger 2A', 'Rieger 2A'), ('Stevens', 'Stevens'), ('Klopfer', 'Klopfer'), ('Jeanne', 'Jeanne'), ('Other', 'Other')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='reedsdata',
            name='reed_ID',
            field=models.CharField(max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Reed ID can only contain letters, numbers, hyphens, and underscores', regex='^[A-Za-z0-9_-]+$')]),
        ),
        migrations.AlterField(
            model_name='reedsdata',
            name='shaper',
            field=models.CharField(blank=True, choices=[('', ''), ('Mack', 'Mack'), ('Philadelphia', 'Philadelphia'), ('Stevens', 'Stevens'), ('Pfeiffer', 'Pfeiffer'), ('Klopfer', 'Klopfer'), ('Jeanne', 'Jeanne'), ('Rieger', 'Rieger'), ("Reeds 'n Stuff", "Reeds 'n Stuff"), ('Gilbert', 'Gilbert'), ('Prestini', 'Prestini'), ('Other', 'Other')], default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='reedsdata',
            name='temperature',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Temperature in Celsius', max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='reedsdata',
            name='thickness',
            field=models.FloatField(blank=True, default=None, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(200)]),
        ),
        migrations.CreateModel(
            name='UserParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reedsdata.parameter')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reedsdata_userparameters', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CaneMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_float', models.FloatField(blank=True, null=True)),
                ('value_text', models.CharField(blank=True, max_length=20, null=True)),
                ('step', models.IntegerField(default=1)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('cane', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reedsdata.cane')),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reedsdata.parameter')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('cane', 'parameter')},
            },
        ),
    ]
