# Generated by Django 4.2.20 on 2026-03-29 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reedsdata', '0016_cane_parameter_remove_reedsdata_diamater_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reedsdata',
            name='instrument',
            field=models.CharField(choices=[('oboe', 'Oboe'), ('bassoon', 'Bassoon'), ('english_horn', 'English Horn'), ('oboe_damore', "Oboe d'Amore"), ('contrabassoon', 'Contrabassoon')], max_length=20, null=True),
        ),
    ]
