# Generated by Django 4.2.20 on 2026-03-29 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reedsdata', '0017_alter_reedsdata_instrument'),
    ]

    operations = [
        migrations.AddField(
            model_name='reedsdata',
            name='period',
            field=models.CharField(blank=True, choices=[('modern', 'Modern'), ('classical', 'Classical'), ('baroque', 'Baroque')], max_length=20, null=True),
        ),
    ]
