# Generated by Django 4.2.20 on 2026-03-29 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reedsdata', '0018_reedsdata_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reedsdata',
            name='instrument',
            field=models.CharField(choices=[('oboe', 'Oboe'), ('bassoon', 'Bassoon'), ('english_horn', 'English Horn'), ('oboe_damore', "Oboe d'Amore"), ('contrabassoon', 'Contrabassoon')], default='oboe', max_length=20),
        ),
        migrations.AlterField(
            model_name='reedsdata',
            name='period',
            field=models.CharField(choices=[('modern', 'Modern'), ('classical', 'Classical'), ('baroque', 'Baroque')], default='modern', max_length=20),
        ),
    ]
