# Generated by Django 4.2.20 on 2026-03-29 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reedsdata', '0019_alter_reedsdata_instrument_alter_reedsdata_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reedsdata',
            name='instrument',
            field=models.CharField(blank=True, choices=[('oboe', 'Oboe'), ('bassoon', 'Bassoon'), ('english_horn', 'English Horn'), ('oboe_damore', "Oboe d'Amore"), ('contrabassoon', 'Contrabassoon')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='reedsdata',
            name='period',
            field=models.CharField(blank=True, choices=[('modern', 'Modern'), ('classical', 'Classical'), ('baroque', 'Baroque')], max_length=20, null=True),
        ),
    ]
