# Generated by Django 4.2.20 on 2026-04-02 07:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reedsdata', '0020_alter_reedsdata_instrument_alter_reedsdata_period'),
    ]

    operations = [
        migrations.CreateModel(
            name='PinnedReed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('reed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pinned_by', to='reedsdata.reedsdata')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pinned_reeds', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'reed')},
            },
        ),
    ]
